version: "3"

services:
  rtc-translator:
    build: .
    container_name: rtc-translator
    ports:
      - 6969:6969
    environment:
      - PYTHONUNBUFFERED=1
    # volumes:
    #   - .:/tf
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
